permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo

name: Deploy Website to S3 bucket
on:
  push:
    paths:
      - 'projects/cloud_resume/**'
      - '!projects/**'
#     branches:
#     - main

jobs:
  deploy:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        role-to-assume: arn:aws:iam::438207642063:role/github-actions-role
        role-duration-seconds: 900 # the ttl of the session, in seconds.
        aws-region: us-east-1

    - name: Copy files to the site with the AWS CLI
      run: |
        aws s3 sync . s3://trinatking.com
