permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo

name: Deploy Website to S3 bucket
on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: unbuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::438207642063:role/github-actions-role
        role-duration-seconds: 900 # the ttl of the session, in seconds.
        aws-region: us-east-1

    - name: AWS S3 Sync with CloudFront Cache invalidation
      uses: kersvers/s3-sync-with-cloudfront-invalidation@v1.0.0
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        DISTRIBUTION_ID: 'E1DEVWCUSCYOPW'
        SOURCE_DIR: 'cloud_resume' # optional: defaults to entire repository

